// notes_en.js — generated by build_notes_en.py from notes_en_source.json.
// Interpretive English redrafts of your notes, keyed by item id. Do not edit
// by hand. Re-run: python build_notes_en.py
window.CULTURE_NOTES_EN = {
 "walkabout": "A masterpiece. An improbable, doomed communion between worlds that should never have met — Roeg distils the surreal essence of Australia and finds an aching, wordless beauty in life at the very edge of the world.",
 "ikiru": "Every bit the equal of 12 Angry Men — it brings together cinema's very best instincts, and the result stands first-class in both what it says and how it's made.",
 "la-haine": "Deftly narrated and directed, with a razor-sharp cross-section of society; it slackens a little midway, but I walked out of the cinema shaken — naturalism in its purest form.",
 "possession": "As if The Shining and The Exorcist were fused and redlined — astonishing. Cosmic performances, execution, makeup, and acting. Wow.",
 "burning": "How much can be conveyed through such subtle, immaculate craft from the whole ensemble. The second half didn't fully satisfy me, but it's intensely hypnotic cinema.",
 "12-angry-men": "Quite literally — the execution of this format is cinema absolute.",
 "oldboy": "So much here lands exceptionally — the direction above all, and the balance it strikes between comedy and drama. But the ending wrecked me like nothing has in a very long time.",
 "apocalypse-now": "A steady descent into depth and the grotesque, its heavy atmosphere matched by a production as monumental as its subject. Artful, psychologically charged, resonant on many levels — and a superb adaptation."
};
