// tmdb_meta.js — generated by update_tmdb_meta.py. TMDB poster art (+ vote,
// runtime) for items lacking a hand-picked poster. Do not edit by hand.
// Re-run: python update_tmdb_meta.py [--limit N]
window.CULTURE_TMDB_META = {
 "premier-automne": {
  "poster": "https://image.tmdb.org/t/p/w500/tPLq8twBxiNQLo2oRdczyoaBSqJ.jpg",
  "vote": 7.6,
  "runtime": 10
 },
 "iron-boy": {
  "poster": "https://image.tmdb.org/t/p/w500/v65oWT7LsyHEMRs16RXWH8gNfqD.jpg",
  "runtime": 89
 },
 "pierwsza-milosc": {
  "poster": "https://image.tmdb.org/t/p/w500/tS0INoioxxYKfNqBEpr5eSWQ5JP.jpg",
  "vote": 6.6,
  "runtime": 52
 },
 "urzad": {
  "poster": "https://image.tmdb.org/t/p/w500/8eK9f7mfG2ZZVDvOlW97kF6JGp6.jpg",
  "vote": 6.7,
  "runtime": 6
 },
 "hinterland": {
  "poster": "https://image.tmdb.org/t/p/w500/Q5iQ8V5I80dYmckXQERgCY0jC0.jpg",
  "runtime": 43
 },
 "solo-na-ugorze": {
  "poster": "https://image.tmdb.org/t/p/w500/bSygzjRTwWoDUepPyQ6JVe4SAPL.jpg",
  "vote": 5.6,
  "runtime": 7
 },
 "tori-no-uta": {
  "poster": "https://image.tmdb.org/t/p/w500/qfezAZyYCzWIB2LWp5PQ7ZDtJj1.jpg",
  "vote": 6.2,
  "runtime": 35
 },
 "imp-f-child": {
  "poster": "https://image.tmdb.org/t/p/w500/p8uTx2xm72vXqI0H4W5kU3ku9ND.jpg",
  "vote": 6.3,
  "runtime": 137
 },
 "imp-f-day-night": {
  "poster": "https://image.tmdb.org/t/p/w500/hn2tOtidoYZ0D56jR4yknpdP1mU.jpg",
  "vote": 7.7,
  "runtime": 6
 },
 "imp-f-dekalog-v": {
  "poster": "https://image.tmdb.org/t/p/w500/t9V2nTq15i9cmfbieglzaCW4IJk.jpg",
  "vote": 7.1,
  "runtime": 56
 },
 "imp-f-dekalog-viii": {
  "poster": "https://image.tmdb.org/t/p/w500/bJ60dOPRq3M0Dkbpnp5jrl2UfVX.jpg",
  "vote": 7.3,
  "runtime": 55
 },
 "imp-f-fear-and-loathing-in-las-vegas": {
  "poster": "https://image.tmdb.org/t/p/w500/tisNLcMkxryU2zxhi0PiyDFqhm0.jpg",
  "vote": 7.2,
  "runtime": 118
 },
 "imp-f-kr-tki-film-o-zabijaniu": {
  "poster": "https://image.tmdb.org/t/p/w500/k7sk4yNdoXY7iwp1M9QTZuBDiJS.jpg",
  "vote": 7.6,
  "runtime": 85
 },
 "imp-f-red-dragon": {
  "poster": "https://image.tmdb.org/t/p/w500/ou9ZKA2cms02b7CdCdVqGkKu0O0.jpg",
  "vote": 7.0,
  "runtime": 124
 },
 "imp-f-zdj-cie": {
  "poster": "https://image.tmdb.org/t/p/w500/kUhmsgKNJSNDMVRCqc8vGTDs7G0.jpg",
  "vote": 6.7,
  "runtime": 32
 },
 "imp-f-a-beautiful-mind": {
  "poster": "https://image.tmdb.org/t/p/w500/rEIg5yJdNOt9fmX4P8gU9LeNoTQ.jpg",
  "vote": 7.9,
  "runtime": 135
 },
 "imp-f-a-bronx-tale": {
  "poster": "https://image.tmdb.org/t/p/w500/sDbO6LmLYtyqAoFTPpRcMgPSCEO.jpg",
  "vote": 7.9,
  "runtime": 121
 },
 "imp-f-a-king-in-new-york": {
  "poster": "https://image.tmdb.org/t/p/w500/e6KtBoiXa5D3LLZtiMCkiqIDnZv.jpg",
  "vote": 6.7,
  "runtime": 104
 },
 "imp-f-aftersun": {
  "poster": "https://image.tmdb.org/t/p/w500/evKz85EKouVbIr51zy5fOtpNRPg.jpg",
  "vote": 7.7,
  "runtime": 101
 },
 "imp-f-age-of-sail": {
  "poster": "https://image.tmdb.org/t/p/w500/iUhwWf0wmpns4QZk8MBR8fPODaF.jpg",
  "vote": 7.1,
  "runtime": 12
 },
 "imp-f-3808": {
  "poster": "https://image.tmdb.org/t/p/w500/q2GE3qqj5tecyJ31ifjUjPrrzo8.jpg",
  "vote": 7.5,
  "runtime": 112
 },
 "imp-f-american-psycho": {
  "poster": "https://image.tmdb.org/t/p/w500/9uGHEgsiUXjCNq8wdq4r49YL8A1.jpg",
  "vote": 7.4,
  "runtime": 102
 },
 "imp-f-andrey-rublyov": {
  "poster": "https://image.tmdb.org/t/p/w500/jUihkn16SwPPIjuOyo6orHWUep6.jpg",
  "vote": 7.9,
  "runtime": 183
 },
 "imp-f-annie-hall": {
  "poster": "https://image.tmdb.org/t/p/w500/dEtjPywhDbAXYjoFfhBC4U9unU7.jpg",
  "vote": 7.7,
  "runtime": 93
 },
 "imp-f-artistic-creation": {
  "poster": "https://image.tmdb.org/t/p/w500/zkMpObDmvp4pdNZDCIez1w58PVr.jpg",
  "vote": 6.2,
  "runtime": 1
 },
 "imp-f-att-d-da-ett-barn": {
  "poster": "https://image.tmdb.org/t/p/w500/f3TJR1MultxpmSYLvGy4uDrgvb6.jpg",
  "vote": 6.8,
  "runtime": 10
 },
 "imp-s-870863": {
  "poster": "https://image.tmdb.org/t/p/w500/mIanPgm20EZyASoPayPUrDmeEH1.jpg",
  "vote": 7.7,
  "runtime": 58
 },
 "imp-f-bab-el-hadid": {
  "poster": "https://image.tmdb.org/t/p/w500/zm8ET6PSfPT6pozgvjR7htaZFjy.jpg",
  "vote": 7.4,
  "runtime": 77
 },
 "imp-f-baraka": {
  "poster": "https://image.tmdb.org/t/p/w500/ldEuJQ4z7zEvL7iXraESWBUfQcz.jpg",
  "vote": 8.2,
  "runtime": 97
 }
};
