#!/usr/bin/env python3
"""update_tmdb_meta.py — pull TMDB poster art (+ vote, runtime) into tmdb_meta.js.

OMDb often lacks a Poster for brand-new festival films, so cover/stack items render
as a bare glyph. TMDB has the art. update_cast.py already resolves each title to a
TMDB id, so we reuse that resolver, then read poster_path / vote_average / runtime
from the detail call.

Output (own file, merged at runtime as item.tmdbPoster when the item has no
hand-picked `poster`):
  window.CULTURE_TMDB_META = { "<itemId>": {"poster": "<url>", "vote": 7.2, "runtime": 89} }

Items that ALREADY carry a hand-picked `poster:` in data.js/imports.js are skipped
(their art wins anyway). Resumable (tmdb_meta_cache.json). Order: data.js favorites
→ imports → wishlist.
Run: python update_tmdb_meta.py [--dry-run] [--limit N] [--force]
TMDB_API_KEY must be in .env.
"""
import json, os, re, sys, time
try: sys.stdout.reconfigure(encoding='utf-8')
except Exception: pass
import update_cast as uc      # load_env, http_get, tmdb_search, TMDB
import update_omdb as uo      # parse_items, MOVIE, TV, FILES

SD    = os.path.dirname(os.path.abspath(__file__))
OUT   = os.path.join(SD, 'tmdb_meta.js')
CACHE = os.path.join(SD, 'tmdb_meta_cache.json')
IMG   = 'https://image.tmdb.org/t/p/w500'
DRY   = '--dry-run' in sys.argv
FORCE = '--force' in sys.argv
LIMIT = next((int(sys.argv[i + 1]) for i, a in enumerate(sys.argv)
              if a == '--limit' and i + 1 < len(sys.argv)), None)


def ids_with_poster():
    """ids whose line carries a hand-picked `poster:` — skip these, their art wins."""
    have = set()
    for name in ('data.js', 'imports.js'):
        p = os.path.join(SD, name)
        if not os.path.exists(p):
            continue
        for line in open(p, encoding='utf-8'):
            if 'poster:' in line or '"poster"' in line:
                m = re.search(r"""\bid"?\s*:\s*['"]([^'"]+)['"]""", line)
                if m:
                    have.add(m.group(1))
    return have


def fetch_meta(key, item):
    kind = 'movie' if item['medium'] in uo.MOVIE else 'tv'
    tid, score = uc.tmdb_search(kind, key, item['en'] or item['title'], item['year'] or 0)
    if not tid:
        return None
    d = uc.http_get(f'{uc.TMDB}/{kind}/{tid}?api_key={key}') or {}
    pp = d.get('poster_path')
    if not pp:
        return None
    out = {'poster': IMG + pp}
    if d.get('vote_average'):
        out['vote'] = round(d['vote_average'], 1)
    rt = d.get('runtime') or (d.get('episode_run_time') or [None])[0]
    if rt:
        out['runtime'] = rt
    return out


def main():
    env = uc.load_env()
    key = env.get('TMDB_API_KEY')
    if not key:
        print('No TMDB_API_KEY in .env'); return

    skip = ids_with_poster()
    items, seen = [], set()
    for name, rank in uo.FILES:
        p = os.path.join(SD, name)
        if not os.path.exists(p):
            continue
        for it in uo.parse_items(p):
            if it['id'] in seen or it['id'] in skip:
                continue
            seen.add(it['id']); it['_rank'] = rank; items.append(it)
    items.sort(key=lambda x: (x['_rank'], -x['rating'], x['title']))

    cache = json.load(open(CACHE, encoding='utf-8')) if os.path.exists(CACHE) else {}
    todo = [x for x in items if FORCE or x['id'] not in cache]
    if LIMIT:
        todo = todo[:LIMIT]
    print(f'{"[DRY] " if DRY else ""}poster-less film/TV: {len(items)}  ·  '
          f'skipped (hand-art): {len(skip)}  ·  to fetch now: {len(todo)}')
    if DRY:
        for it in todo[:15]:
            print(f"  {it['id']:30} {it['en'] or it['title']} ({it['year']})")
        print('\n--dry-run: no calls, nothing written.'); return

    found = 0
    for n, it in enumerate(todo, 1):
        meta = fetch_meta(key, it)
        cache[it['id']] = meta          # cache misses (None) too, so we don't retry forever
        if meta:
            found += 1
        if n % 25 == 0:
            json.dump(cache, open(CACHE, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
            print(f'  … {n}/{len(todo)}, {found} posters')
        time.sleep(0.05)

    json.dump(cache, open(CACHE, 'w', encoding='utf-8'), ensure_ascii=False, indent=1)
    good = {k: v for k, v in cache.items() if v}
    header = ('// tmdb_meta.js — generated by update_tmdb_meta.py. TMDB poster art (+ vote,\n'
              '// runtime) for items lacking a hand-picked poster. Do not edit by hand.\n'
              '// Re-run: python update_tmdb_meta.py [--limit N]\n'
              'window.CULTURE_TMDB_META = ')
    open(OUT, 'w', encoding='utf-8').write(header + json.dumps(good, ensure_ascii=False, indent=1) + ';\n')
    print(f'\nDone. {found} posters this run; tmdb_meta.js holds {len(good)} '
          f'(of {len(cache)} looked up).')
    remaining = len([x for x in items if x['id'] not in cache])
    if remaining:
        print(f'{remaining} still un-fetched — re-run `python update_tmdb_meta.py --limit N`.')


if __name__ == '__main__':
    main()
